server:
  port: 8080

openai:
  api:
    key: ${OPENAI_API_KEY}

spring:
  application:
    name: remediation-app

logging:
  level:
    root: INFO
    com.chung.cyber.code.remediator: DEBUG

# Database configuration
# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/yourdatabase
#     username: yourusername
#     password: yourpassword
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
